"""Writes src/FdDraft.View/Toolbars/ToolIconData.g.cs from icons.py.

    python3 tools/icons/gen_cs.py          (from the repo root)
    python3 tools/icons/preview.py tools/icons/icons.html   (a gallery to look at them)

Each icon becomes a few lines of a tiny drawing language that ToolIcons.Parse reads:
    L x1 y1 x2 y2 role width dash
    P role width dash fill|svg-path
    C cx cy r role width dash fill
    R x y w h role width dash fill
    T x y size anchor role rot ax ay|text
dash is 0/1; fill is '-' (none), '=' (the stroke colour) or a role name.
"""
import os, sys
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from icons import ICONS

def num(v):
    s = ("%.3f" % float(v)).rstrip("0").rstrip(".")
    return "0" if s in ("-0", "") else s

def fill_of(o):
    f = o.get("fill")
    if not f:
        return "-"
    return f if isinstance(f, str) else "="

def encode(prims):
    out = []
    for p in prims:
        k = p[0]
        if k == "t":
            _, x, y, txt, role, sz, anchor = p[:7]
            o = p[7] if len(p) > 7 else {}
            rot = o.get("rot", 0); ax, ay = o.get("at", (x, y))
            if "rot" in o:
                x, y = ax, ay
            out.append(f"T {num(x)} {num(y)} {num(sz)} {anchor} {role} {num(rot)} {num(ax)} {num(ay)}|{txt}")
            continue
        role, o = p[-2], p[-1]
        w = num(o.get("w", 1.5)); d = "1" if o.get("dash") else "0"
        if k == "l":
            out.append(f"L {num(p[1])} {num(p[2])} {num(p[3])} {num(p[4])} {role} {w} {d}")
        elif k == "p":
            out.append(f"P {role} {w} {d} {fill_of(o)}|{p[1]}")
        elif k == "c":
            out.append(f"C {num(p[1])} {num(p[2])} {num(p[3])} {role} {w} {d} {fill_of(o)}")
        elif k == "r":
            out.append(f"R {num(p[1])} {num(p[2])} {num(p[3])} {num(p[4])} {role} {w} {d} {fill_of(o)}")
    return "\n".join(out)

def cs_string(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n") + '"'

lines = [
    "// <auto-generated> by tools/icons/gen_cs.py from tools/icons/icons.py - edit those, not this file. </auto-generated>",
    "using System.Collections.Generic;",
    "",
    "namespace FdDraft.View.Toolbars",
    "{",
    "    public static partial class ToolIcons",
    "    {",
    "        private static readonly Dictionary<string, string> Source = new Dictionary<string, string>",
    "        {",
]
for key in sorted(ICONS):
    lines.append(f"            [{cs_string(key)}] = {cs_string(encode(ICONS[key]['prims']))},")
lines += ["        };", "    }", "}", ""]
root = os.path.abspath(os.path.join(HERE, "..", ".."))
dest = os.path.join(root, "src", "FdDraft.View", "Toolbars", "ToolIconData.g.cs")
with open(dest, "w", encoding="utf-8", newline="\n") as f:
    f.write("\n".join(lines))
print(f"{len(ICONS)} icons -> {os.path.relpath(dest, root)}")
